FROM node:18-alpine

# Set working directory
WORKDIR /usr/src/app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install --production

# Copy application source code
COPY . .

# Set environment variable
ENV NODE_ENV=production

# Expose application port
EXPOSE 3000

# Start the app
CMD ["node", "app.js"]
